"""
Investment Recommendation Schema
"""

from pydantic import BaseModel


class Recommendation(BaseModel):
    """
    Final recommendation generated by Portfolio Agent.
    """

    action: str

    confidence: float

    allocation_percentage: float

    investment_horizon: str

    risk_level: str