"""
Risk Analysis Output Schema
"""

from pydantic import BaseModel, Field


class RiskAnalysisOutput(BaseModel):
    """
    Structured risk assessment generated by the LLM.
    """

    overall_risk: str = Field(
        ...,
        description="Overall investment risk (Low, Medium, High)."
    )

    business_risk: str = Field(
        ...,
        description="Assessment of business and operational risks."
    )

    financial_risk: str = Field(
        ...,
        description="Assessment of financial risks."
    )

    market_risk: str = Field(
        ...,
        description="Assessment of market and macroeconomic risks."
    )

    news_risk: str = Field(
        ...,
        description="Assessment of risks from recent news and events."
    )

    technical_risk: str = Field(
        ...,
        description="Assessment of technical/chart-based risks."
    )

    valuation_risk: str = Field(
        ...,
        description="Risk associated with the current valuation."
    )

    risk_score: float = Field(
        ...,
        ge=0,
        le=100,
        description="Overall risk score between 0 and 100."
    )

    recommendation: str = Field(
        ...,
        description="Recommended action considering identified risks."
    )

    summary: str = Field(
        ...,
        description="Overall risk summary."
    )
    