"""
Technical Analysis Output Schema

Structured output returned by the Technical Analysis Agent.
"""

from pydantic import BaseModel, Field


class TechnicalAnalysisOutput(BaseModel):
    """
    Structured technical analysis generated by the LLM.
    """

    trend: str = Field(
        ...,
        description="Overall market trend (Bullish, Bearish, Sideways)."
    )

    trend_reason: str = Field(
        ...,
        description="Reasoning behind the identified trend."
    )

    momentum: str = Field(
        ...,
        description="Momentum assessment (Strong, Moderate, Weak)."
    )

    momentum_reason: str = Field(
        ...,
        description="Reasoning behind the momentum analysis."
    )

    volatility: str = Field(
        ...,
        description="Volatility level (Low, Normal, High)."
    )

    volatility_reason: str = Field(
        ...,
        description="Reasoning behind the volatility assessment."
    )

    volume: str = Field(
        ...,
        description="Volume analysis (Increasing, Decreasing, Neutral)."
    )

    volume_reason: str = Field(
        ...,
        description="Reasoning behind the volume analysis."
    )

    trading_signal: str = Field(
        ...,
        description="Final recommendation (Strong Buy, Buy, Hold, Sell, Strong Sell)."
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=100,
        description="Confidence score between 0 and 100."
    )

    summary: str = Field(
        ...,
        description="Overall summary of the technical analysis."
    )