"""
Valuation Analysis Output Schema
"""

from pydantic import BaseModel, Field


class ValuationAnalysisOutput(BaseModel):
    """
    Structured valuation analysis generated by the LLM.
    """

    valuation: str = Field(
        ...,
        description="Overall valuation (Undervalued, Fairly Valued, Overvalued)."
    )

    valuation_reason: str = Field(
        ...,
        description="Reason for the valuation conclusion."
    )

    margin_of_safety: str = Field(
        ...,
        description="Margin of safety assessment."
    )

    fair_value_opinion: str = Field(
        ...,
        description="Opinion on whether the current market price is attractive."
    )

    investment_outlook: str = Field(
        ...,
        description="Short- to medium-term investment outlook."
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=100,
        description="Confidence score between 0 and 100."
    )

    summary: str = Field(
        ...,
        description="Overall valuation summary."
    )